### ISSUE TITLE
Error on python3.8

### ISSUE THREAD

**Issue by Tim4497** [snowskeleton/snowcrypt#9]
When I try to use the tool with python 3.8 it throws:

```
Traceback (most recent call last):
  File "/Users/t.winkler/.pyenv/versions/3.8.17/bin/snowcrypt", line 5, in <module>
    from snowcrypt.main import main
  File "/Users/t.winkler/.pyenv/versions/3.8.17/lib/python3.8/site-packages/snowcrypt/main.py", line 67, in <module>
    activation_bytes: str | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```
It should specify the python version to use

**Comment by snowskeleton** [comment]
Try reinstalling fro pypi and running this again. It looks like I previously fixed this problem by adding
```
from __future__ import annotations
```
but never pushed it to pypi. I just pushed the change now.
